export const aboutMe = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'About Me',
    headline2: 'My Name is',
    headline: 'Sung Wook Yoo',
    description: 'Inspiring Full Stack Developer who has 6+ years development experience. Familiar to work in Angular framework and NodeJS.',
    buttonLabel: 'Resume',
    imgStart: false,
    img: require('../../assets/images/profile-pic.png'),
    alt: 'Sung Wook Yoo Profile Picture',
    dark: true,
    primary: true,
    darkText: true,
    linkURL: '',
    deployedURL: 'https://github.com/yoowook1207',
    button1Label: 'GitHub'
};

export const homeObjOne = {
    id: 'project1',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Project 1',
    headline2: 'Application of',
    headline: 'Power Home Remodeling Group, LLC',
    description: 'Developed a single page application using Angular 13, TypeScript, NgRx, Bootstrap and NestJS. Participated in designing the style guide and branding. Implemented auth service using reactive forms to ensure current user info, using OAuth 2.0 to hold web token for authentication, and using bcrypt to hash users’ passwords. Implemented page scrolling event that loads items sequentially using Renderer2. ',
    imgStart: true,
    img: require('../../assets/images/PHRG.png'),
    alt: 'PHR Logo',
    dark: true,
    primary: true,
    darkText: false,
    linkURL: '',
    deployedURL: 'https://powerhrg.com/',
    button1Label: 'Website',
}

export const homeObjTwo = {
    id: 'project2',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Project 2',
    headline2: 'Find your next home',
    headline: 'Homesnap',
    description: "Developed a single page application using Angular 11. Implemented a live chat function in the corner of the website, using LiveChat APIs. Built a products comparison page using NgRx library to hold up four products to compare.",
    imgStart: false,
    img: require('../../assets/images/Homesnap.png'),
    alt: 'Homesnap',
    dark: true,
    primary: true,
    darkText: true,
    linkURL: '',
    deployedURL: 'https://www.homesnap.com/',
    button1Label: 'Website',
};

export const homeObjThree = {
    id: 'project3',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Project 3',
    headline2: 'Treatment tracker in your hand',
    headline: 'Abilify MyCite',
    description: 'Developed an application using Angular 8/9, Express, and MySQL. Updated from Angular 8 to 9 while developing the application. Designed UI features and developed pages including monthly schedule, doctors contact book, daily condition, and login/signup page.',
    buttonLabel: 'GitHub',
    imgStart: true,
    img: require('../../assets/images/MyCite.png'),
    alt: 'Abilify MyCite Application',
    dark: true,
    primary: true,
    darkText: false,
    linkURL: '',
    deployedURL: 'https://www.otsuka-us.com/products-solutions-and-patient-support/abilify-mycite-information',
    button1Label: 'Official Docs'
}

export const homeObjFour = {
    id: 'project4',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Project 4',
    headline2: 'Aviation Advisory Services',
    headline: 'mba Aviation',
    description: 'Responsible for attractive design and developing user interfaces in single page applications using Angular. Collaborated with the REDBOOK application team to implement application info-page. Implemented scroll sensitive header using Angular Material.',
    buttonLabel: 'GitHub',
    imgStart: false,
    img: require('../../assets/images/mba.png'),
    alt: 'mba Aviation Homepage',
    dark: true,
    primary: true,
    darkText: true,
    linkURL: '',
    deployedURL: 'https://www.mba.aero/',
    button1Label: 'Deployed'
}

// export const homeObjFive = {
//     id: 'project5',
//     lightBg: false,
//     lightText: true,
//     lightTextDesc: true,
//     topLine: 'Project 1',
//     headline2: 'Kitchen to Table application',
//     headline: 'Bryss',
//     description: 'Web-app running on React.js. A pre-made meal prep service that delivers health and tasty meals straight to user. Database that user create is stored in connected MongoDB Atlas. Users can create their account, delivery address, reviews, or check out.',
//     buttonLabel: 'GitHub',
//     imgStart: true,
//     img: require('../../assets/images/Bryss.png'),
//     alt: 'Bryss Homepage',
//     dark: true,
//     primary: true,
//     darkText: false,
//     linkURL: 'https://github.com/RyanRobCodes/BRYSS-Meals',
//     deployedURL: 'https://bryss-meals.herokuapp.comlala/',
//     button1Label: 'Deployed'
// }